# Generated by Django 5.2.3 on 2025-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.CharField(max_length=5000),
        ),
    ]
